---
abstract: 'Compute distance matrix for any distance metric'
author:
  - 'Chad A. Davis <chad.a.davis@gmail.com>'
build_requires:
  Algorithm::Cluster: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-DistanceMatrix
requires:
  Moose: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Algorithm-DistanceMatrix
version: 0.01
